model:
    arch: fcn8s
data:
    dataset: pascal
    train_split: train_aug
    val_split: val
    img_rows: 128
    img_cols: 128
    path: ./datasets/VOCdevkit/VOC2012/
    sbd_path: ./datasets/VOCdevkit/VOCaug/
training:
    train_iters: 60
    batch_size: 1
    val_interval: 1000
    n_workers: 8
    print_interval: 50
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: /content/drive/My Drive/Colab Notebooks/pytorch_semseg/fcn/fcn8s_pascal_best_model.pkl
